# Generated by Django 4.0.1 on 2022-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.SlugField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
